/*
 * uln2003.c
 *
 *  Created on: 03 mag 2017
 *      Author: raidenfox
 */

#include "uln2003.h"

void ULN2003_Init(){

	GPIO_InitTypeDef GPIO_InitStruct;

	__HAL_RCC_GPIOB_CLK_ENABLE();

	/* Reset */
	GPIO_InitStruct.Pin = GPIO_IN1 | GPIO_IN2 | GPIO_IN3 | GPIO_IN4 ;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_NOPULL;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
	HAL_GPIO_Init(GPIO_IN_PORT, &GPIO_InitStruct);

	HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN1,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN2,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN3,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN4,GPIO_PIN_RESET);

}

void ULN2003_TestMotor(){
	for(int j = 0; j < 1000; j++){
		for(int i = 0; i < 512; i++){
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN1,GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN2,GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN3,GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN4,GPIO_PIN_SET);

			HAL_Delay(1);

			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN1,GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN2,GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN3,GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN4,GPIO_PIN_SET);

			HAL_Delay(1);

			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN1,GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN2,GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN3,GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN4,GPIO_PIN_RESET);

			HAL_Delay(1);

			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN1,GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN2,GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN3,GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN4,GPIO_PIN_RESET);

			HAL_Delay(1);

			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN1,GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN2,GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN3,GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN4,GPIO_PIN_RESET);

			HAL_Delay(1);

			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN1,GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN2,GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN3,GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN4,GPIO_PIN_RESET);

			HAL_Delay(1);

			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN1,GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN2,GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN3,GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN4,GPIO_PIN_RESET);

			HAL_Delay(1);

			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN1,GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN2,GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN3,GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN4,GPIO_PIN_SET);

			HAL_Delay(1);
			}
		}

		HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN1,GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN2,GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN3,GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIO_IN_PORT,GPIO_IN4,GPIO_PIN_RESET);
}
